name: Build and push image

on:
  repository_dispatch:
    types: [release,master]
env:
  USER: "kksudo"
  DOCKER_IMAGE: "odyssey-docker"
  ODYSSEY_GIT_REPO: "yandex/odyssey"
  ODYSSEY_MAIN_BRANCH: "master"
  DOCKER_REG_GIT: "docker.pkg.github.com"
  DOCKER_REPO_GIT: "odyssey-docker/odyssey"
  CI_TAG: "CI_${GITHUB_RUN_NUMBER}"
  # TODO: create latest tag
  DEV_TAG: "develop"
  CI_REGISTRY_IMAGE: "${DOCKER_REG_GIT}/${USER}/${DOCKER_REPO_GIT}"

jobs:
#  Add DockerLint Job  and validate
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Login to gitHub docker registry
        run:  docker login ${DOCKER_REG_GIT} -u ${USER} -p ${{secrets.GH_TOKEN}}
      - name: Build from new tag
        if: ${{ github.event.client_payload.tag }}
        run: |
          echo "New tag=>${{ github.event.client_payload.id }}"
          docker build --pull --cache-from ${CI_REGISTRY_IMAGE}:${DEV_TAG} --build-arg ODYSSEY_VERSION=${{ github.event.client_payload.id }} -t ${DOCKER_IMAGE}:${CI_TAG} .
      - name: Build from latest commit ID
        if: ${{ github.event.client_payload.commit }}
        run: |
          echo "New latest master commit_id=>${{ github.event.client_payload.id }}"
          docker build --build-arg ODYSSEY_VERSION=${ODYSSEY_MAIN_BRANCH} -t ${DOCKER_IMAGE}:${CI_TAG} .
#      - name: Add docker tags
#      - name: Exit with error if one of above jobs failed
#      - name: Write new latest data to the .env
#      - name: Push image to GitHub packages
#      - name: Push Event to build image in DockerHub
