name: build image

on:
  repository_dispatch:
    types: [release,master]
env:
  USER: "kksudo"
  DOCKER_IMAGE: "odyssey-docker"
  ODYSSEY_GIT_REPO: "yandex/odyssey"
  DOCKER_REG_GIT: "docker.pkg.github.com"
  DOCKER_REPO_GIT: "odyssey-docker/odyssey"

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "New tag=>${{ github.event.client_payload.id }}"
        if: ${{ github.event.client_payload.tag }}
      - run: echo "New latest master commit_id=>${{ github.event.client_payload.id }}"
        if: ${{ github.event.client_payload.commit }}
      - name: Build image new image
        run: docker build --build-arg ODYSSEY_VERSION=${{ github.event.client_payload.id }} -t ${DOCKER_IMAGE}:${GITHUB_ACTION} .
