name: build image

on:
  repository_dispatch:
    types: [build_release,build_master]

jobs:
  buildNewRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - run: |
          env
          echo ${{ toJson(github.event.client_payload) }}
          echo "New tag=>${{ github.event.client_payload.tag }}"
          echo "New latest master commit_id=>${{ github.event.client_payload.commit }}"
      - name: Build image with new release
        if: ${{ github.event.client_payload.tag }}
        run: |
          echo "New tag=>${{ github.event.client_payload.tag }}"
      - name: Build image from latest master branch
        if: ${{ github.event.client_payload.commit }}
        run: |
          echo "New latest master commit_id=>${{ github.event.client_payload.commit }}"
