name: watch-remote-repo

on:
#  schedule:
#    - cron:  '* */1 * * *'
  push:
    branches:
      - develop
env:
  USER: "kksudo"
  ODYSSEY_GIT_REPO: "yandex/odyssey"
jobs:
    watch-repo:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@master
        - name: Get the latest up-to-date data from a remote repository
          id: get_remote_vars
          run: |
            echo ::set-env name=LATEST_REMOTE_RELEASE::$(echo $(curl --silent https://api.github.com/repos/${ODYSSEY_GIT_REPO}/releases/latest | grep '"tag_name":' | cut -d'"' -f4))
            echo ::set-env name=LATEST_REMOTE_MASTER_COMMIT_ID::$(echo $(git ls-remote git://github.com/${ODYSSEY_GIT_REPO}.git HEAD | awk '{ print $1}'))
        - name: ===DEBUG===
          run: |
            echo
            echo
            echo "-- Environment variables ----------------------------------------------"
            env
            echo "-----------------------------------------------------------------------"
        