name: watch-remote-repo

on:
#  schedule:
#    - cron:  '*/15 * * * *'
  push:
    branches:
      - develop

env:
  USER: "kksudo"

jobs:
    watch-repo:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@master
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2
#       touch continue or sudo touch /continue to return job
      - name: Read local env
        id: set_vars
        run: |
          vars=$(echo $(cat .github/workflows/env.json))
          echo "::set-output name=_context::$vars"
      - name: Echo vars
        env:
          MY_CONTEXT: ${{ steps.set_vars.outputs._context }}
        run: |
          echo "$MY_CONTEXT"
          echo "${{ fromJson(steps.set_vars.outputs._context) }}"

#    build-event:
#      needs: watch-repo
#      runs-on: ubuntu-latest
#      steps:
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          event-type: build
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'