name: watch-remote-repo

on:
#  schedule:
#    - cron:  '*/15 * * * *'
  push:
    branches:
      - develop

env:
  USER: "kksudo"

jobs:
    watch-repo:
      runs-on: ubuntu-latest
      steps:
      - name: Read local env
        id: set_vars
        run: |
          vars=`cat .github/workflows/env.json`
          echo "::set-output name=matrix::$vars"
      - name: Echo vars
        run: echo "${{fromJson(steps.set_var.outputs.matrix).OD_MAIN_COMMIT_ID}}"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
#       touch continue or sudo touch /continue

#    build-event:
#      needs: watch-repo
#      runs-on: ubuntu-latest
#      steps:
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          event-type: build
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'