name: watch-remote-repo

on:
#  schedule:
#    - cron:  '* */1 * * *'
  push:
    branches:
      - develop
env:
  USER: "kksudo"
  ODYSSEY_GIT_REPO: "yandex/odyssey"
jobs:
    watch-repo:
      runs-on: ubuntu-latest
      steps:
#        TODO: uncomment for debugging session via ssh
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2
#       touch continue or sudo touch /continue to return job
      - name: Read local env
        id: get_vars
        run: |
          # Get local vars
          vars=$(echo $(cat .github/workflows/env.json))
          echo '::set-env name=OD_RELEASE::$(echo $(fromJson($vars).OD_RELEASE))'
          echo '::set-env name=OD_MAIN_COMMIT_ID::$(echo $(fromJson($vars).OD_MAIN_COMMIT_ID))'
          # Get remote vars
          latest_release=$(curl --silent https://api.github.com/repos/${ODYSSEY_GIT_REPO}/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          latest_main_commit_id=$(git ls-remote git://github.com/${ODYSSEY_GIT_REPO}.git HEAD | awk '{ print $1}')
          echo '::set-env name=LATEST_RELEASE::$(echo $latest_release)'
          echo '::set-env name=LATEST_MAIN_COMMIT_ID::$(echo $latest_main_commit_id)'
      - name: Get latest version the remote repository
        run: |
          echo "LATEST_RELEASE=> ${LATEST_RELEASE}, whereas local release is=> ${OD_RELEASE}"
          echo "LATEST_MAIN_COMMIT_ID=> ${LATEST_MAIN_COMMIT_ID}, whereas local release is=> ${OD_MAIN_COMMIT_ID}"


# TODO: Read output context
#        run: |
#          echo "$MY_CONTEXT"
#          echo "${{ fromJson(steps.get_vars.outputs._context).OD_MAIN_COMMIT_ID }}"

# TODO: send event to build new image
#    build-event:
#      needs: watch-repo
#      if: success()
#      runs-on: ubuntu-latest
#      steps:
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          event-type: build
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'